server:
  port: 8083
kafka:
  producer:
    employee:
      topic: employee-avro
      acks: all
      bootstrapServer: localhost:29092
      schemaRegistry: http://localhost:8081
      applicationName: ${spring.application.name}
spring:
  application:
    name: demo-jpa-with-kafka
  cache:
    type: redis
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?createIfNotExists=true
    username: sa
    password: sa
  redis:
    host: localhost
    port: 6379
    timeout: 60000
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - env
          - beans
