server:
  port: 8083
kafka:
  producer:
    employee:
      bootstrapServer: broker:29092
      schemaRegistry: http://schema-registry:8081
spring:
  datasource:
    url: jdbc:mysql://mydb:3306/db?createIfNotExists=true
  redis:
    host: redis